# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: On Push Run

on: push

env:
  screener_pull_stockprice_DIR: screener_pull_stockprice

jobs:
  Stock-Price:
    name: Stock Info
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: kbbabu/screener_pull_stockprice
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.screener_pull_stockprice_DIR }}
        run: pip install -r requirements.txt 

    - name: Nifty 50 stock information
      run: python ${{ env.screener_pull_stockprice_DIR }}/nifty_50_data.py
      
      shell: sh
