# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: On Push Run

on: push

jobs:
  Stock-Price:
    name: Stock Info
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install the python version needed
    
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: execute py script # nifty_50_data.py
      env:
        SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python nifty_50_data.py
    
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main           
